# BYD Song Pro - Extra??o de ficha t?cnica

Este notebook l? o PDF da ficha t?cnica, limpa o texto extra?do e monta um `DataFrame` com duas colunas: `Atributo veicular` e `Valor`.

Quando o PDF apenas lista o recurso sem um valor expl?cito, o notebook usa `Presente`.

In [1]:
from pathlib import Path
import fitz
import pandas as pd

from vehicle_pdf_utils import clean_text, build_dataframe
from song_pro_rows import get_feature_rows

In [3]:
pdf_path = Path("Ficha Técnica-Song Pro-GS-JUL24.pdf")
doc = fitz.open(pdf_path)
doc.page_count

6

In [4]:
for page_number in range(1, doc.page_count + 1):
    text = clean_text(doc.load_page(page_number - 1).get_text("text"))
    print(f"--- PAGE {page_number} ---")
    print(text[:1200])
    print()

--- PAGE 1 ---
DM-i GS

--- PAGE 2 ---
ESPECIFICAÇÕES E CONFIGURAÇÕESDM-i GSTração DianteiraPotência combinada (cv) 235Aceleração 0-100 km (s) 7,9Velocidade máxima (km) 185Consumo energético (MJ/km) 0,56Motor elétricoTorque máximo (N•m)300Potência máxima (cv)197Motor a combustãoTorque máximo (N•m)122 @4500 rpmPotência máxima (cv)98 @ 6000 rpmTipo de energiaComprimento (mm)Largura (mm)Altura (mm)Raio de giro (m) Distância do solo (mm) (em ordem de marcha) Volume do porta-malas (l) Tamanho do tanque de combustível (l) Pneus Kit reparo Híbrido plug-inSuspensão dianteira McPherson4.7381.8601.710Entre-eixos (mm) 2.7125,8156520/133952Suspensão traseira Freio dianteiro Freio traseiro MultilinkFreio a disco ventiladoFreio a disco225/60R18

--- PAGE 3 ---
Lanterna traseira LEDFaróis dianteiros de LED Luz central dianteira tipo contínua Faróis de neblina traseirosAjuste manual da altura do farolFaróis automáticos (acendimento automático)Luzes diurnas LED Luz de placa traseira Função "Follow Me Home"(iluminação temporizada após desligar o carro)Tipo de bateriaCapacidade da bateria (kWh)Bateria Blade (LFP)18,3Autonomia elétrica NEDC (km)110Função de descarga do veículo (V2L) Forma de carregamento + potência (kW) Carregamento AC (até 6,6)Painel de instrumentos de 8,8" em LCD Volante multifuncional Carregamento sem fio para celularTomada 12VBancos com revestimento premium sustentávelBancos traseiros bipartidos rebatíveisAjuste elétrico do banco do motorista em 6 direçõesSistema ISOFIX de fixação de cadeira infantilInterior

--- PAGE 4 ---
Sensor de estacionamento dianteiro com 2 radares Sensor de estacionamento traseiro com 4 radares Chave presencial Ajuste da coluna de direção manual em 4 direçõesAirbag frontal do motoristaAirbag frontal do passageiroAirbags laterais dianteiras Airbags de cortina lateral (dianteira e traseira)Cintos de segurança dianteiroscom pré-tensionamento e limitação de força Aviso sonoro de cinto de segurança do motorista não afiveladoAviso de cinto de segurança traseiro não afiveladoDesbloqueio elétrico da tampa do tanque de combustívelDesbloqueio elétrico do porta-malasAbertura elétrica do porta-malasDesembaçador elétrico do vidro traseiroAjuste elétrico dos espelhos retrovisoresEspelho retrovisor com desembaçadorRebatimento elétrico dos retrovisoresAviso sonoro de cinto de segurança do passageiro não afiveladoSegurança e conveniênciaSistema de direção assistida elétrica (C-EPS) Freios ABS Controle de traçãoSistema de distribuição eletrônica da força de frenagemAssistência de partida em rampas Função de frenagem confortávelControle de cruzeiro Sistema direto de monitoramento de pressão dos pneus (TPMS) Controle Eletrônico de Estabilidade (VDC) Freio de estacionamento eletrônico Limpador de

--- PAGE 5 ---
Veículo: 6 anos sem limite de quilometragem(sistema elétrico PHEV + baixa tensão + chassis)Bateria Blade: 8 anos sem limite de quilometragem*O cartão NFC deve ser adquirido à parte diretamente na concessionária.Saída de ar para o banco traseiroFiltro de ar PM2.5 Zonas de ar-condicionado2Sistema DiLink Atualização remota por OTA (Over-the-Air) Pacote de tráfego 4G GPS integrado Conexão e espelhamento Apple CarPlay e Android Comandos de voz Tela flutuante rotativa (pol) Câmera 360 graus Compatibilidade com cartão NFC* Sistema de som6 alto-falantes12,8Entrada USB3 (tipo A) / 1 (tipo C)

--- PAGE 6 ---
Paz no trânsito começa por você.

In [5]:
# Montagem da tabela final
rows = get_feature_rows()
df = build_dataframe(rows)
df

                  Atributo veicular                    Valor
0                            Tração                Dianteira
1           Potência combinada (cv)                      235
2           Aceleração 0-100 km (s)                      7,9
3            Velocidade máxima (km)                      185
4        Consumo energético (MJ/km)                     0,56
..                              ...                      ...
83    Tela flutuante rotativa (pol)                     12,8
84                 Câmera 360 graus                 Presente
85  Compatibilidade com cartão NFC*                 Presente
86                   Sistema de som          6 alto-falantes
87                      Entrada USB  3 (tipo A) / 1 (tipo C)

[88 rows x 2 columns]

In [ ]:
# Se quiser inspecionar o resultado em formato tabular
df

                  Atributo veicular                    Valor
0                            Tração                Dianteira
1           Potência combinada (cv)                      235
2           Aceleração 0-100 km (s)                      7,9
3            Velocidade máxima (km)                      185
4        Consumo energético (MJ/km)                     0,56
..                              ...                      ...
83    Tela flutuante rotativa (pol)                     12,8
84                 Câmera 360 graus                 Presente
85  Compatibilidade com cartão NFC*                 Presente
86                   Sistema de som          6 alto-falantes
87                      Entrada USB  3 (tipo A) / 1 (tipo C)

[88 rows x 2 columns]

In [8]:
df['Valor'].tolist()

['Dianteira',
 '235',
 '7,9',
 '185',
 '0,56',
 '300',
 '197',
 '122 @4500 rpm',
 '98 @ 6000 rpm',
 'Híbrido plug-in',
 '4.738',
 '1.860',
 '1.710',
 '2.712',
 '5,8',
 '156',
 '520/1339',
 '52',
 '225/60R18',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Bateria Blade (LFP)',
 '18,3',
 '110',
 'Presente',
 'Carregamento AC (até 6,6)',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 '6 anos sem limite de quilometragem (sistema elétrico PHEV + baixa tensão + chassis)',
 '8 anos sem limite de quilometragem',
 'Presente',
 'Presente',
 '2',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 'Presente',
 '12,8',
 'Presente',
 'Presente',
 '6 alto-falantes',
 '3 (tipo A) / 1 (tipo C)']